namespace: haproxy

stack:
  defines: process-group
  runnable-list:
    - haproxy/haproxy-1
    - haproxy/haproxy-2
    - haproxy/haproxy-1
  variables:  
    haproxy-port: 8080
    host-port: 8080
    haproxy-image-tag: 2.7.1
    backend-runnable: 
    backend-runnable-service: 