namespace: haproxy-cluster

stack:
  defines: process-group
  runnable-list:
    - haproxy-cluster/haproxy-1
    - haproxy-cluster/haproxy-2
    - haproxy-cluster/haproxy-3 
  variables:  
    haproxy-port: 8080
    host-port: 8080
    haproxy-image-tag: 2.7.1
    backend-runnable: 
    backend-runnable-service: 